### ISSUE TITLE
Make gifs work

### ISSUE THREAD

**Issue by gsimone** [gsimone/use-capture#2]
Gifs need a worker, it's included in the original lib but needs to be publicly accessible ( solution could be to just copy it, tbh )

**Comment by mattrossman** [comment]
Was this closed to indicate that it's fixed? Cause I am getting an error with `format: 'gif'`

![image](https://user-images.githubusercontent.com/22670878/100485974-1c3ca780-30d0-11eb-994b-96b4eb2c5f68.png)

**Comment by gsimone** [comment]
Hey Matt, I never got to making gifs work, since I opted for making videos and converting them, if you want to take a look PRs are welcome. I'm waiting for a new version of ccapture and for some changes we planned in r3f, for a new release of this

**Comment by mattrossman** [comment]
I guess I will just stick with using video output, because I have to perform optimization steps anyways in order to get GIFs with appropriate quality and size for Twitter. Ideally I'd want use-capture to handle the optimization parts too so I could get a Twitter-ready GIF in one step, but maybe that's beyond the scope of this project.

**Comment by gsimone** [comment]
I eventually want to make this a one-stop solution for that, but it'll have to wait for more manageble code - or I should look into how to rewrite ccapture -
